### PR TITLE
swisseph updgrade to latest version (2.06) - 2017

### PR DESCRIPTION
**Pull request by atkit**
source: http://www.astro.com/ftp/swisseph/swe_unix_src_2.06.tar.gz

### CODE REVIEW

**Comment by mivion** [comment]
Could you check this for newer node versions? io.js is outdated.

**Comment by atkit** [comment]
I run it on node.js (v6.9.1).

**Comment by mivion** [comment]
Thanks a lot for help, one more things:
- Lets remove iojs from travis
- Lets leave only node versions: 6.x and 7.x

**Comment by atkit** [comment]
ook:)

**Comment by atkit** [comment]
hi @mivion, let's merge or close ?

**Comment by mivion** [comment]
Sorry for wait...

**Comment by atkit** [comment]
thanks, no problem

**Pull request merged**
