### PR TITLE
add props using SEFLG_EQUATORIAL and SEFLG_XYZ bits (issue # 23)

### PR DESCRIPTION
**Pull request by knyazhe1**
* calc
* calc_ut
* fixstar
* fixstar_ut
* nod_aps
* nod_aps_ut

examples/issue-23.js

### CODE REVIEW

**Comment by gordalina** [comment]
I'd add some documentation in `README.md` to specify this behaviour.

**Comment by mivion** [comment]
Thanks, good work.
Would you change **rectascention** to **rectAscention**, to correct naming convention?
Also, add some notes in README.md

**Comment by knyazhe1** [comment]
well, changed to **rectAscension**, add some notes to README.md.
but my english is poor :flushed:

**Comment by mivion** [comment]
Thank you. Looks good.

**Comment by gordalina** [comment]
`package.json` version should be updated to `1.0.0` and a new tag should be pushed.

**Comment by mivion** [comment]
I'll do it soon separately.

**Pull request merged**
